featureClass:
  firstorder: null
  glcm: null
  gldm: null
  glrlm: null
  glszm: null
  ngtdm: null
  shape: null
imageType:
  Exponential: {}
  Gradient: {}
  LBP2D: {}
  LBP3D: {}
  LoG:
    sigma:
    - 1
  Logarithm: {}
  Original: {}
  Square: {}
  SquareRoot: {}
  Wavelet: {}
setting:
  additionalInfo: false
  binCount: 16
  correctMask: true
  geometryTolerance: 1e-6
  label: 1
  normalize: true
  normalizeScale: 1000
  resampledPixelSpacing:
  - 1.0
  - 1.0
  - 1.0
  resegmentMode: sigma
